#pragma once

#include "h-basic.h"

enum gamepad_button_id {
    GAMEPAD_BUTTON_INVALID = -1,
    GAMEPAD_BUTTON_SOUTH = 0,
    GAMEPAD_BUTTON_EAST,
    GAMEPAD_BUTTON_WEST,
    GAMEPAD_BUTTON_NORTH,
    GAMEPAD_BUTTON_BACK,
    GAMEPAD_BUTTON_GUIDE,
    GAMEPAD_BUTTON_START,
    GAMEPAD_BUTTON_LEFT_STICK,
    GAMEPAD_BUTTON_RIGHT_STICK,
    GAMEPAD_BUTTON_LEFT_SHOULDER,
    GAMEPAD_BUTTON_RIGHT_SHOULDER,
    GAMEPAD_BUTTON_DPAD_UP,
    GAMEPAD_BUTTON_DPAD_DOWN,
    GAMEPAD_BUTTON_DPAD_LEFT,
    GAMEPAD_BUTTON_DPAD_RIGHT,
    GAMEPAD_BUTTON_MISC1,
    GAMEPAD_BUTTON_RIGHT_PADDLE1,
    GAMEPAD_BUTTON_LEFT_PADDLE1,
    GAMEPAD_BUTTON_RIGHT_PADDLE2,
    GAMEPAD_BUTTON_LEFT_PADDLE2,
    GAMEPAD_BUTTON_TOUCHPAD,
    GAMEPAD_BUTTON_MISC2,
    GAMEPAD_BUTTON_MISC3,
    GAMEPAD_BUTTON_MISC4,
    GAMEPAD_BUTTON_MISC5,
    GAMEPAD_BUTTON_MISC6,
    GAMEPAD_BUTTON_COUNT
};

#define GAMEPAD_TRIGGER_COUNT 2
#define GAMEPAD_STICK_DIR_COUNT 4

#define GAMEPAD_STICK_DIR_UP 0
#define GAMEPAD_STICK_DIR_DOWN 1
#define GAMEPAD_STICK_DIR_LEFT 2
#define GAMEPAD_STICK_DIR_RIGHT 3

#define GAMEPAD_BIND_NONE -1
#define GAMEPAD_BIND_SHIFT -2
#define GAMEPAD_BIND_CTRL -3
#define GAMEPAD_BIND_ALT -4
#define INPUT_BIND_CONFIRM -5
#define TOUCH_PANE_BIND_INHERIT -6

#define TOUCH_PANE_BUTTON_COLS 3
#define TOUCH_PANE_BUTTON_ROWS 8
#define TOUCH_PANE_BUTTON_COUNT (TOUCH_PANE_BUTTON_COLS * TOUCH_PANE_BUTTON_ROWS)
#define TOUCH_PANE_LABEL_LEN 24
#define TOUCH_PANE_PANEL_COUNT 2
#define TOUCH_PANE_PANEL_MAIN 0
#define TOUCH_PANE_PANEL_SECOND 1

/* Transitional aliases for existing touch-pane identifiers. */
#define SDL_TOUCH_PANE_BUTTON_COLS TOUCH_PANE_BUTTON_COLS
#define SDL_TOUCH_PANE_BUTTON_ROWS TOUCH_PANE_BUTTON_ROWS
#define SDL_TOUCH_PANE_BUTTON_COUNT TOUCH_PANE_BUTTON_COUNT
#define SDL_TOUCH_PANE_LABEL_LEN TOUCH_PANE_LABEL_LEN
#define SDL_TOUCH_PANE_PANEL_COUNT TOUCH_PANE_PANEL_COUNT
#define SDL_TOUCH_PANE_PANEL_MAIN TOUCH_PANE_PANEL_MAIN
#define SDL_TOUCH_PANE_PANEL_SECOND TOUCH_PANE_PANEL_SECOND
