/*
 * Copyright (C) 2025-2026 Sil-More contributors
 *
 * This file is part of Sil-More.
 *
 * Sil-More is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * Sil-More is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See LICENSE.md
 * for more details.
 */

#pragma once

#include "gamepad-config.h"

#define TOUCH_SWIPE_DIR_COUNT GAMEPAD_STICK_DIR_COUNT
#define TOUCH_SWIPE_DIR_UP GAMEPAD_STICK_DIR_UP
#define TOUCH_SWIPE_DIR_DOWN GAMEPAD_STICK_DIR_DOWN
#define TOUCH_SWIPE_DIR_LEFT GAMEPAD_STICK_DIR_LEFT
#define TOUCH_SWIPE_DIR_RIGHT GAMEPAD_STICK_DIR_RIGHT

#define TOUCH_BIND_TOP_PANEL_OPEN -7
#define TOUCH_BIND_TOP_PANEL_CLOSE -8

#define SDL_TOUCH_MENU_CATEGORY_INVENTORY_EQUIPMENT 0
#define SDL_TOUCH_MENU_CATEGORY_SUPPLY 1
#define SDL_TOUCH_MENU_CATEGORY_OTHER 2
#define SDL_TOUCH_MENU_CATEGORY_COUNT 3

#define SDL_TOUCH_PROFILE_TOUCH_PANE 0
#define SDL_TOUCH_PROFILE_CORNERS 1
#define SDL_TOUCH_PROFILE_ROUND_WHEEL 2
#define SDL_TOUCH_PROFILE_COUNT 3

#define SDL_TOUCH_MOVEMENT_ON 0
#define SDL_TOUCH_MOVEMENT_OFF 1
#define SDL_TOUCH_MOVEMENT_LONG_PRESS_ONLY 2

#define SDL_TOUCH_ZONE_OVERLAY_OFF 0
#define SDL_TOUCH_ZONE_OVERLAY_MARKERS 1
#define SDL_TOUCH_ZONE_OVERLAY_BORDERS 2
#define SDL_TOUCH_ZONE_OVERLAY_BORDERS_LABELS 3
#define SDL_TOUCH_ZONE_OVERLAY_COUNT 4

#define SDL_TOUCH_ZONE_CENTER_LEFT_TAP 0
#define SDL_TOUCH_ZONE_CENTER_LEFT_LONG_TAP 1
#define SDL_TOUCH_ZONE_CENTER_RIGHT_TAP 2
#define SDL_TOUCH_ZONE_CENTER_RIGHT_LONG_TAP 3
#define SDL_TOUCH_ZONE_CENTER_BINDING_COUNT 4

#define SDL_TOUCH_CORNER_UP_DOWN_LEFT 0
#define SDL_TOUCH_CORNER_UP_DOWN_RIGHT 1
#define SDL_TOUCH_CORNER_ACTION_TOP_TAP 0
#define SDL_TOUCH_CORNER_ACTION_TOP_LONG_TAP 1
#define SDL_TOUCH_CORNER_ACTION_BOTTOM_TAP 2
#define SDL_TOUCH_CORNER_ACTION_BOTTOM_LONG_TAP 3
#define SDL_TOUCH_CORNER_ACTION_BINDING_COUNT 4

#define SDL_TOUCH_TOP_PANEL_MODE_SHORT 0
#define SDL_TOUCH_TOP_PANEL_MODE_LONG 1
#define SDL_TOUCH_TOP_PANEL_MODE_COUNT 2
#define SDL_TOUCH_TOP_PANEL_SHORT_BUTTON_COUNT 4
#define SDL_TOUCH_TOP_PANEL_BUTTON_COUNT 6
