/*
 * Copyright (C) 2025-2026 Sil-More contributors
 *
 * This file is part of Sil-More.
 */

#ifndef INCLUDED_CMD_DEPTH_BONUS_H
#define INCLUDED_CMD_DEPTH_BONUS_H

#define MIN_DEPTH_BONUS_UNITS_PER_DEPTH 2
#define MIN_DEPTH_ITEM_BONUS_DEEP_CALL_EQUIPPED \
    (3 * MIN_DEPTH_BONUS_UNITS_PER_DEPTH)
#define MIN_DEPTH_ITEM_BONUS_DEEP_CALL_INVENTORY \
    (MIN_DEPTH_ITEM_BONUS_DEEP_CALL_EQUIPPED / 2)
#define MIN_DEPTH_ITEM_BONUS_CRUEL_BLOW_EQUIPPED \
    MIN_DEPTH_ITEM_BONUS_DEEP_CALL_EQUIPPED
#define MIN_DEPTH_ITEM_BONUS_PERMA_CURSE (5 * MIN_DEPTH_BONUS_UNITS_PER_DEPTH)

#endif /* INCLUDED_CMD_DEPTH_BONUS_H */
